### ISSUE TITLE
Virtualbox 5 guest editions

### ISSUE THREAD

**Issue by dominikzogg** [boxcutter/debian#14]
Hello @annawake

Would be cool, if you would update the virtualbox guest additions to 5.0.

Regards @dominikzogg

**Comment by dominikzogg** [comment]
@annawake any news on this?

**Comment by dominikzogg** [comment]
@grafjo any news on this?

**Comment by grafjo** [comment]
@dominikzogg have you tried running packer with latest vagrant, packer and virtualbox? Works form me!

**Comment by dominikzogg** [comment]
@grafjo would be cool if the newest version would be on: https://atlas.hashicorp.com/boxcutter/boxes/debian80

**Comment by dominikzogg** [comment]
@grafjo i use it for https://github.com/dominikzogg/vagrant-php/tree/v1, there was no release since 3months now. Is this box not supported anymore? Cause the ubuntu boc for example get an update few days ago.

**Comment by grafjo** [comment]
@dominikzogg I don't know ... maybe @annawake will release a new version soon. I'm not using the public boxes for certain reasons.

**Comment by dominikzogg** [comment]
@annawake did you drop the support for debian8?

**Comment by annawake** [comment]
New boxes have been built

**Comment by dominikzogg** [comment]
@annawake thank you
