### ISSUE TITLE
Using deborphan breaks Salt versioned install

### ISSUE THREAD

**Issue by mafrosis** [boxcutter/debian#17]
The use of `deborphan` in `minimize.sh` means that a bunch of necessary packages for Salt are removed when doing a versioned install of Salt via the `cm_version` var.

I spent a while playing around with `deborphan`, but couldn't come up with any way to mark the relevant packages as `manual` or similar which would make `deborphan` ignore them.

This is because Salt is installed from python source using `pip` when doing a versioned install. Salt's dependencies are installed via `apt`, and thus are "orphans".

Thoughts? Yet another `-var` and ENV var to avoid using `deborphan` during the packer build? I think that might be preferable to assuming that only a salt versioned install might benefit from ditching `deborphan`.

**Comment by annawake** [comment]
`deborphan` has been removed
