### ISSUE TITLE
Debian 7 and 8 installation asks for input/confirmation and fails to login to VM

### ISSUE THREAD

**Issue by mgruner** [boxcutter/debian#44]
Both the Debian 7 and 8 install processes ask for input (select grub boot device) and final confirmation before reboot. Of course, this breaks fully automated box generation. Maybe an issue with preseeding?

![bildschirmfoto 2016-11-15 um 10 11 46](https://cloud.githubusercontent.com/assets/211281/20299604/faee1a3e-ab1b-11e6-92ab-2935d7b0600e.png)

**Comment by mgruner** [comment]
Besides that, after the initial installation and first reboot, packer is unable to login to the VM:

```
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
```

This is packer 0.11.0 with VirtualBox 5.1.8.

**Comment by annawake** [comment]
Can't reproduce on packer 0.12.0 and VirtualBox 5.1.10. The error is indicative of not being able to access the preseed file, which would in turn produce a dud image as it wouldn't install the vagrant user/keys properly - packer fires up a web server to offer them up to the VM. Without more detailed log output, I don't really know how to help.

**Comment by mgruner** [comment]
Hello @annawake and thanks a lot for your feedback! I can confirm that it works correctly with packer 0.12.0.
