### ISSUE TITLE
Please update boxes at https://app.vagrantup.com/boxes

### ISSUE THREAD

**Issue by htgoebel** [boxcutter/debian#55]
Debian 8.8 and Debian 9 boxes are still missing at https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=boxcutter+debian

Please update. Thanks.

**Comment by misheska** [comment]
We'll still keep the template sources up here on github, but I'm retiring the binary archive. It's a lot of work keeping the templates built and keeping up with all the vagrant/desktop virtualization changes, and I don't think it's worth the effort to do it anymore, given all the options that exist via Docker and cloud providers.
