### ISSUE TITLE
Debian boxes not found - 404 http

### ISSUE THREAD

**Issue by guilhemmarchand** [boxcutter/debian#58]
Hi, 

Could you please verify and correct the availability of the boxes ?

https://app.vagrantup.com/boxcutter/boxes/debian8

And all other boxes result in a 404 not found... so bad

Thank you very much !!!

**Comment by misheska** [comment]
We'll still keep the template sources up here on github, but I'm retiring the binary archive. It's a lot of work keeping the templates built and keeping up with all the vagrant/desktop virtualization changes, and I don't think it's worth the effort to do it anymore, given all the options that exist via Docker and cloud providers.

**Comment by stephenreay** [comment]
If anyone is looking for ready to go Debian boxes, we (Koalephant) are publishing our fork (https://github.com/Koalephant/debian) of the box cutter Debian boxes at https://app.vagrantup.com/koalephant

Parallels and VirtualBox only for now, VMWare coming soon.
