### ISSUE TITLE
Debian 9 VMware tool

### ISSUE THREAD

**Issue by TheAngryByrd** [boxcutter/debian#64]
When building debian 9 for vmware this loops constantly

```
    vmware-iso: What is the location of the "ifconfig" program on your
    vmware-iso: machine?
    vmware-iso: The answer "" is invalid.  It must be the complete name of a binary file.
```

Since debian9 doesn't have ifconfig anymore a fix would be to add `net-tools` to the prelude-jessie.cfg.  Would you like a PR for it?

**Comment by rasa** [comment]
Sure!
